"""
Kam Air Mock & Reference Service Layer (Prototype)
--------------------------------------------------
This module serves as the service-layer mock data provider.
When official Kam Air GDS, Amadeus, Navitaire, or SITA APIs become available,
this service layer can be replaced without modifying frontend client contracts.
"""

KAM_AIR_CITIES = [
    {
        "code": "KBL",
        "name": "Kabul",
        "country": "Afghanistan",
        "airport": "Hamid Karzai International Airport",
        "type": "hub",
        "terminal": "International & Domestic Terminal",
    },
    {
        "code": "DXB",
        "name": "Dubai",
        "country": "United Arab Emirates",
        "airport": "Dubai International Airport",
        "type": "international",
        "terminal": "Terminal 2",
    },
    {
        "code": "IST",
        "name": "Istanbul",
        "country": "Turkey",
        "airport": "Istanbul Airport (IST)",
        "type": "international",
        "terminal": "Main Terminal",
    },
    {
        "code": "DEL",
        "name": "Delhi",
        "country": "India",
        "airport": "Indira Gandhi International Airport",
        "type": "international",
        "terminal": "Terminal 3",
    },
    {
        "code": "JED",
        "name": "Jeddah",
        "country": "Saudi Arabia",
        "airport": "King Abdulaziz International Airport",
        "type": "international",
        "terminal": "North Terminal / Hajj Terminal",
    },
    {
        "code": "MED",
        "name": "Medina",
        "country": "Saudi Arabia",
        "airport": "Prince Mohammad bin Abdulaziz Airport",
        "type": "international",
        "terminal": "Main Terminal",
    },
    {
        "code": "TAS",
        "name": "Tashkent",
        "country": "Uzbekistan",
        "airport": "Islam Karimov Tashkent International Airport",
        "type": "international",
        "terminal": "Terminal 2",
    },
    {
        "code": "ISB",
        "name": "Islamabad",
        "country": "Pakistan",
        "airport": "Islamabad International Airport",
        "type": "international",
        "terminal": "Main Terminal",
    },
    {
        "code": "AUH",
        "name": "Abu Dhabi",
        "country": "United Arab Emirates",
        "airport": "Zayed International Airport",
        "type": "international",
        "terminal": "Terminal A",
    },
    {
        "code": "HEA",
        "name": "Herat",
        "country": "Afghanistan",
        "airport": "Khwaja Abdullah Ansari International Airport",
        "type": "domestic",
        "terminal": "Domestic Terminal",
    },
    {
        "code": "MZR",
        "name": "Mazar-i-Sharif",
        "country": "Afghanistan",
        "airport": "Mawlana Jalaluddin Balkhi International Airport",
        "type": "domestic",
        "terminal": "Domestic Terminal",
    },
    {
        "code": "KDH",
        "name": "Kandahar",
        "country": "Afghanistan",
        "airport": "Ahmad Shah Baba International Airport",
        "type": "domestic",
        "terminal": "Domestic Terminal",
    },
]

KAM_AIR_SCHEDULES = [
    # Kabul <-> Dubai (Daily)
    {
        "flightNumber": "RQ-901",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "DXB",
        "destinationCity": "Dubai",
        "departureTime": "08:30",
        "arrivalTime": "11:45",
        "duration": "3h 45m",
        "frequency": "Daily",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 295,
        "basePriceAFN": 20800,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "DXB Terminal 2",
        "status": "On Time",
    },
    {
        "flightNumber": "RQ-903",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "DXB",
        "destinationCity": "Dubai",
        "departureTime": "16:15",
        "arrivalTime": "19:30",
        "duration": "3h 45m",
        "frequency": "Mon, Wed, Fri, Sun",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 310,
        "basePriceAFN": 21850,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "DXB Terminal 2",
        "status": "Scheduled",
    },
    {
        "flightNumber": "RQ-902",
        "origin": "DXB",
        "originCity": "Dubai",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "13:00",
        "arrivalTime": "16:45",
        "duration": "3h 15m",
        "frequency": "Daily",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 280,
        "basePriceAFN": 19700,
        "stops": 0,
        "terminalDeparture": "DXB Terminal 2",
        "terminalArrival": "KBL Main",
        "status": "On Time",
    },
    {
        "flightNumber": "RQ-904",
        "origin": "DXB",
        "originCity": "Dubai",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "20:45",
        "arrivalTime": "00:30",
        "duration": "3h 15m",
        "frequency": "Mon, Wed, Fri, Sun",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 290,
        "basePriceAFN": 20400,
        "stops": 0,
        "terminalDeparture": "DXB Terminal 2",
        "terminalArrival": "KBL Main",
        "status": "Scheduled",
    },
    # Kabul <-> Istanbul
    {
        "flightNumber": "RQ-101",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "IST",
        "destinationCity": "Istanbul",
        "departureTime": "07:15",
        "arrivalTime": "12:00",
        "duration": "5h 15m",
        "frequency": "Tue, Thu, Sat",
        "aircraft": "Airbus A340-300",
        "basePriceUSD": 520,
        "basePriceAFN": 36600,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "IST Main",
        "status": "On Time",
    },
    {
        "flightNumber": "RQ-102",
        "origin": "IST",
        "originCity": "Istanbul",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "13:30",
        "arrivalTime": "20:15",
        "duration": "5h 15m",
        "frequency": "Tue, Thu, Sat",
        "aircraft": "Airbus A340-300",
        "basePriceUSD": 495,
        "basePriceAFN": 34850,
        "stops": 0,
        "terminalDeparture": "IST Main",
        "terminalArrival": "KBL Main",
        "status": "On Time",
    },
    # Kabul <-> Jeddah (Umrah & Pilgrim Service)
    {
        "flightNumber": "RQ-701",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "JED",
        "destinationCity": "Jeddah",
        "departureTime": "10:30",
        "arrivalTime": "15:00",
        "duration": "5h 00m",
        "frequency": "Tue, Fri, Sun",
        "aircraft": "Airbus A340-300",
        "basePriceUSD": 610,
        "basePriceAFN": 42900,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "JED North Terminal",
        "status": "Scheduled",
    },
    {
        "flightNumber": "RQ-702",
        "origin": "JED",
        "originCity": "Jeddah",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "16:30",
        "arrivalTime": "23:00",
        "duration": "4h 30m",
        "frequency": "Tue, Fri, Sun",
        "aircraft": "Airbus A340-300",
        "basePriceUSD": 590,
        "basePriceAFN": 41500,
        "stops": 0,
        "terminalDeparture": "JED North Terminal",
        "terminalArrival": "KBL Main",
        "status": "Scheduled",
    },
    # Kabul <-> Delhi
    {
        "flightNumber": "RQ-501",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "DEL",
        "destinationCity": "Delhi",
        "departureTime": "09:45",
        "arrivalTime": "12:45",
        "duration": "2h 30m",
        "frequency": "Mon, Wed, Fri",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 240,
        "basePriceAFN": 16900,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "DEL Terminal 3",
        "status": "On Time",
    },
    {
        "flightNumber": "RQ-502",
        "origin": "DEL",
        "originCity": "Delhi",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "14:15",
        "arrivalTime": "16:15",
        "duration": "2h 30m",
        "frequency": "Mon, Wed, Fri",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 230,
        "basePriceAFN": 16200,
        "stops": 0,
        "terminalDeparture": "DEL Terminal 3",
        "terminalArrival": "KBL Main",
        "status": "On Time",
    },
    # Kabul <-> Tashkent
    {
        "flightNumber": "RQ-301",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "TAS",
        "destinationCity": "Tashkent",
        "departureTime": "11:00",
        "arrivalTime": "13:15",
        "duration": "1h 45m",
        "frequency": "Wed, Sat",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 210,
        "basePriceAFN": 14780,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "TAS Terminal 2",
        "status": "Scheduled",
    },
    {
        "flightNumber": "RQ-302",
        "origin": "TAS",
        "originCity": "Tashkent",
        "destination": "KBL",
        "destinationCity": "Kabul",
        "departureTime": "15:00",
        "arrivalTime": "17:15",
        "duration": "1h 45m",
        "frequency": "Wed, Sat",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 200,
        "basePriceAFN": 14080,
        "stops": 0,
        "terminalDeparture": "TAS Terminal 2",
        "terminalArrival": "KBL Main",
        "status": "Scheduled",
    },
    # Kabul <-> Islamabad
    {
        "flightNumber": "RQ-201",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "ISB",
        "destinationCity": "Islamabad",
        "departureTime": "14:00",
        "arrivalTime": "15:30",
        "duration": "1h 00m",
        "frequency": "Mon, Tue, Thu, Sat",
        "aircraft": "Boeing 737-800",
        "basePriceUSD": 160,
        "basePriceAFN": 11260,
        "stops": 0,
        "terminalDeparture": "KBL Main",
        "terminalArrival": "ISB Main",
        "status": "On Time",
    },
    # Domestic: Kabul <-> Herat
    {
        "flightNumber": "RQ-111",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "HEA",
        "destinationCity": "Herat",
        "departureTime": "07:30",
        "arrivalTime": "08:45",
        "duration": "1h 15m",
        "frequency": "Daily",
        "aircraft": "Boeing 737-500",
        "basePriceUSD": 75,
        "basePriceAFN": 5280,
        "stops": 0,
        "terminalDeparture": "KBL Domestic",
        "terminalArrival": "HEA Domestic",
        "status": "Boarding",
    },
    # Domestic: Kabul <-> Mazar-i-Sharif
    {
        "flightNumber": "RQ-121",
        "origin": "KBL",
        "originCity": "Kabul",
        "destination": "MZR",
        "destinationCity": "Mazar-i-Sharif",
        "departureTime": "08:00",
        "arrivalTime": "08:50",
        "duration": "0h 50m",
        "frequency": "Daily",
        "aircraft": "Boeing 737-500",
        "basePriceUSD": 65,
        "basePriceAFN": 4580,
        "stops": 0,
        "terminalDeparture": "KBL Domestic",
        "terminalArrival": "MZR Domestic",
        "status": "Departed",
    },
]

BAGGAGE_RULES = {
    "economy": {
        "checked": "30 kg (1 or 2 pieces)",
        "cabin": "7 kg (1 personal item, max 55 x 40 x 20 cm)",
        "excessPerKgUSD": 10,
        "zamzamAllowance": "5 Liters complimentary per pilgrim on Saudi flights",
    },
    "business": {
        "checked": "40 kg (up to 2 pieces)",
        "cabin": "10 kg (up to 2 pieces)",
        "excessPerKgUSD": 8,
        "zamzamAllowance": "5 Liters complimentary per pilgrim on Saudi flights",
    },
    "prohibitedItems": [
        "Flammable liquids and gases",
        "Explosives or fireworks",
        "Corrosives, acids, wet cell batteries",
        "Unlabeled liquids over 100ml in cabin baggage",
    ],
}

OFFICIAL_SUPPORT_CHANNELS = {
    "kabulHeadquarters": {
        "address": "Kam Air Building, Kabul International Airport Road, Kabul, Afghanistan",
        "phone": "+93 79 977 7777 / +93 20 220 0108",
        "email": "info@kamair.com",
        "hours": "24/7 Operations",
    },
    "dubaiOffice": {
        "address": "Dubai International Airport Terminal 2 & Deira Clock Tower, Dubai, UAE",
        "phone": "+971 4 298 9898",
        "email": "dubai@kamair.com",
    },
    "istanbulOffice": {
        "address": "Istanbul Airport (IST) Terminal Ticket Desk & Sisli, Istanbul, Turkey",
        "phone": "+90 212 234 5678",
        "email": "istanbul@kamair.com",
    },
    "jeddahOffice": {
        "address": "King Abdulaziz International Airport & Al-Madinah Road, Jeddah, KSA",
        "phone": "+966 12 654 3210",
        "email": "jeddah@kamair.com",
    },
}
