# Generated by Django 6.0.1 on 2026-10-07 07:31

import django.db.models.deletion
import flights.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(default=flights.models.generate_pnr, max_length=12, unique=True)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Afghan', max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=10)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=10)),
                ('destination_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('cabin_class', models.CharField(choices=[('Economy', 'Economy Class'), ('Business', 'Business Class')], default='Economy', max_length=20)),
                ('seat_number', models.CharField(default='12A', max_length=10)),
                ('baggage_allowance', models.CharField(default='30 kg checked + 7 kg cabin', max_length=100)),
                ('total_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kam_air_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
